# Generated by Django 4.0 on 2021-12-23 18:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECESubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ece_subject', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ECE Subject')),
            ],
            options={
                'verbose_name': 'ECE Subject',
                'verbose_name_plural': 'ECE Subjects',
            },
        ),
        migrations.CreateModel(
            name='ECEtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ece_topic', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ECE Topic')),
                ('ece_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.ecesubject', verbose_name='ECE Subject')),
            ],
            options={
                'verbose_name': 'ECE Topic',
                'verbose_name_plural': 'ECE Topics',
            },
        ),
        migrations.CreateModel(
            name='QuizECETopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='a description of the quiz', max_length=255, verbose_name='Description')),
                ('url', models.SlugField(help_text='a user friendly url', max_length=60, null=True, verbose_name='user friendly url')),
                ('number_question', models.PositiveIntegerField(blank=True, help_text='Number of question to be answered', null=True, verbose_name='Number of questions')),
                ('stored_score', models.BooleanField(default=False, help_text='If yes, the result of eact attempt by the user will be stored', verbose_name='Score')),
                ('pass_mark', models.SmallIntegerField(blank=True, default=0, help_text='Percentage required to pass exam.', validators=[django.core.validators.MaxValueValidator(70)], verbose_name='Pass Mark')),
                ('success_mark', models.TextField(blank=True, help_text='Displayed if user passes', verbose_name='Success Text')),
                ('fail_mark', models.TextField(blank=True, help_text='Displayed if use fails.', verbose_name='Fail Text')),
                ('ece_subject', models.ForeignKey(max_length=90, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_ece_subjects', to='quiz.ecesubject', verbose_name='ECE Subject')),
                ('ece_topic', models.ForeignKey(max_length=90, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_ecetopics', to='quiz.ecetopic', verbose_name='ECE Topics')),
            ],
            options={
                'verbose_name': ('EXAM IN ECE TOPICS',),
                'verbose_name_plural': 'EXAM IN ECE TOPICS',
            },
        ),
        migrations.CreateModel(
            name='QuizECESubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, help_text='a description of the quiz', max_length=255, verbose_name='Description')),
                ('url', models.SlugField(help_text='a user friendly url', max_length=60, null=True, verbose_name='user friendly url')),
                ('number_question', models.PositiveIntegerField(blank=True, help_text='Number of question to be answered', null=True, verbose_name='Number of questions')),
                ('ece_subjects', models.ForeignKey(max_length=90, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_ecesubjects', to='quiz.ecesubject', verbose_name='ECE Subject')),
            ],
            options={
                'verbose_name': ('Quiz in ECE Subject',),
                'verbose_name_plural': 'EXAM IN ECE SUBJECTS',
            },
        ),
        migrations.CreateModel(
            name='ECESubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ece_subtopic', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ECE Subtopic')),
                ('ece_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.ecetopic', verbose_name='ECE Topic')),
            ],
            options={
                'verbose_name': 'ECE Subtopics',
                'verbose_name_plural': 'ECE Subtopics',
            },
        ),
    ]
