# Generated by Django 3.2.5 on 2021-11-06 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECESubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ece_subject', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ECE Subject')),
            ],
            options={
                'verbose_name': 'ECE Subject',
                'verbose_name_plural': 'ECE Subjects',
            },
        ),
        migrations.CreateModel(
            name='ECEtopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ece_topic', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ECE Topic')),
                ('ece_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.ecesubject', verbose_name='ECE Subject')),
            ],
            options={
                'verbose_name': 'ECE Topic',
                'verbose_name_plural': 'ECE Topics',
            },
        ),
    ]
