# Generated by Django 3.2.5 on 2021-11-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ECEtopics',
            new_name='ECEtopic',
        ),
    ]
