# Generated by Django 3.2.5 on 2021-11-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_ecetopics_ecetopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECESubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ece_subtopic', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ECE Subtopic')),
                ('ece_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.ecetopic', verbose_name='ECE Topic')),
            ],
        ),
    ]
