# Generated by Django 3.2.5 on 2021-11-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_ecesubtopic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecesubtopic',
            options={'verbose_name': 'ECE Subtopics', 'verbose_name_plural': 'ECE Subtopics'},
        ),
    ]
