# Generated by Django 3.2.5 on 2021-11-06 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizecesubject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizecesubject',
            options={'verbose_name': ('Quiz in ECE Subject',), 'verbose_name_plural': 'Quizzes in ECE Subjects'},
        ),
        migrations.AlterField(
            model_name='quizecesubject',
            name='ece_subjects',
            field=models.ForeignKey(max_length=90, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_ecesubjects', to='quiz.ecesubject', verbose_name='ECE Subject'),
        ),
    ]
