# Generated by Django 3.2.5 on 2021-11-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20211107_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizecesubject',
            name='ece_subject',
        ),
    ]
