# Generated by Django 3.2.5 on 2021-11-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_quizecesubject_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizecesubject',
            options={'verbose_name': ('Quiz in ECE Subject',), 'verbose_name_plural': 'Preboard Exam: MATH'},
        ),
    ]
