# Generated by Django 3.2.5 on 2021-11-06 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_quizecetopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizecetopics',
            name='ece_subject',
            field=models.ForeignKey(max_length=90, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_ece_subjects', to='quiz.ecesubject', unique=True, verbose_name='ECE Subject'),
        ),
    ]
