# Generated by Django 3.2.5 on 2021-12-02 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_quizecetopics_ece_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizecetopics',
            name='ece_subject',
            field=models.ForeignKey(max_length=90, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_ece_subjects', to='quiz.ecesubject', verbose_name='ECE Subject'),
        ),
    ]
