# Generated by Django 3.2.5 on 2021-12-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_quizecetopics_ece_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizecetopics',
            name='ece_subject',
        ),
        migrations.RemoveField(
            model_name='quizecetopics',
            name='ece_topic',
        ),
        migrations.DeleteModel(
            name='QuizECESubject',
        ),
        migrations.DeleteModel(
            name='QuizECETopics',
        ),
    ]
