# Generated by Django 3.2.5 on 2021-12-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_quizecesubject_quizecetopics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizECETopics',
        ),
    ]
