# Generated by Django 3.2.5 on 2021-12-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_quizecetopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizecetopics',
            name='url',
            field=models.SlugField(help_text='a user friendly url', max_length=60, null=True, verbose_name='user friendly url'),
        ),
    ]
