# Generated by Django 4.0 on 2021-12-23 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(help_text='Enter the question text that you want to displayed', max_length=1000, verbose_name='Question')),
                ('figure', models.ImageField(blank=True, null=True, upload_to='insert', verbose_name='Figure')),
                ('correct', models.BooleanField(default=False, help_text='Is this a correct answer?', verbose_name='Correct')),
                ('difficulty', models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], default=0, verbose_name='Difficulty Level')),
                ('optionA', models.CharField(max_length=200, null=True)),
                ('optionB', models.CharField(max_length=200, null=True)),
                ('optionC', models.CharField(max_length=200, null=True)),
                ('optionD', models.CharField(max_length=200, null=True)),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Enter the answers that you want to displayed', max_length=1000, null=True, verbose_name='ANSWER')),
                ('solution', models.TextField(blank=True, help_text='Explanation to be shown after the question has been answered.', max_length=2000, verbose_name='Explanation')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.ecesubject', verbose_name='ECE Subject')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.ecesubtopic', verbose_name='ECE Subtopic')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.ecetopic', verbose_name='ECE Topic')),
            ],
            options={
                'verbose_name': ('Exam Item',),
                'verbose_name_plural': 'Exam items',
            },
        ),
    ]
