# Generated by Django 3.2.5 on 2021-12-03 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0019_quizecetopics_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Enter the question text that you want to displayed', max_length=1000, verbose_name='Question')),
                ('figure', models.ImageField(blank=True, null=True, upload_to='insert', verbose_name='Figure')),
                ('solution', models.TextField(blank=True, help_text='Explanation to be shown after the question has been answered.', max_length=2000, verbose_name='Explanation')),
                ('difficulty', models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], default=0, verbose_name='Difficulty Level')),
                ('answer_order', models.CharField(blank=True, choices=[('content', 'Content'), ('none', 'None')], help_text=' The order in which multiple choice answer options are displayed to the user', max_length=30, null=True, verbose_name='Answer order')),
                ('answer', models.CharField(help_text='Enter the answers that you want to displayed', max_length=1000, null=True, verbose_name='Content')),
                ('correct', models.BooleanField(default=False, help_text='Is this a correct answer?', verbose_name='Correct')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.ecesubject', verbose_name='ECE Subject')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.ecesubtopic', verbose_name='ECE Subtopic')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.ecetopic', verbose_name='ECE Topic')),
            ],
            options={
                'verbose_name': ('Exam Item',),
                'verbose_name_plural': 'Exam items',
            },
        ),
    ]
