# Generated by Django 3.2.5 on 2021-12-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0002_remove_item_answer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='optionA',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='optionB',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='optionC',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='optionD',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='answer',
            field=models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4')], help_text='Enter the answers that you want to displayed', max_length=1000, null=True, verbose_name='ANSWER'),
        ),
    ]
