# Generated by Django 3.2.5 on 2021-12-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0003_auto_20211203_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Enter the answers that you want to displayed', max_length=1000, null=True, verbose_name='ANSWER'),
        ),
    ]
